apiVersion: v1
kind: Service
metadata:
  name: service-2048
  namespace: game-2048
  labels:
    app: game-2048
spec:
  type: NodePort
  selector:
    app: game-2048
  ports:
  - port: 80
    targetPort: 80
    protocol: TCP
    name: http